import type { Metadata } from "next";
import Head from "next/head";
import { Geist, Roboto_Slab } from "next/font/google";
import "@/app/styles/globals.scss";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto_Slab = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`${roboto_Slab.variable}`}>
        <div className="bodyWrapper" id="main-content">
          <Navbar />
          <div className="mainWrapper d-flex">
            <Sidebar />
              <main className="mainContent">
                {children}
              </main>
              <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
